# set PATH for Linux
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
export TMPDIR=/tmp/

homedir=$( getent passwd "$USER" | cut -d: -f6 )
export HOME=$homedir

# disable kptr to lookup symbol of kernel functions
psk=/proc/sys/kernel/kptr_restrict
if [ -f $psk ]; then echo 0 > $psk; fi